spring:
  datasource:
    url: jdbc:mysql://localhost:31006/gssg-assets?useSSL=false&serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true&logger=Slf4JLogger&profileSQL=false&maxQuerySizeToLog=100000
    username: root
    password: local-password-123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  exposed:
    generate-ddl: true

logging.level.Exposed: debug
