spring:
  profiles:
    active:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      default_batch_fetch_size: 1000
    open-in-view: false
  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:testdb}
    driverClassName: org.h2.Driver
    username: ${JDBC_USERNAME:sa}
    password: ${JDBC_PASSWORD:}
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%mdc{transactionId}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  pathsToMatch: /api/**

application:
  jwt:
    secreat: ${SECREAT_KEY:207CEEDB92830C105C3F5B25008DBBE47FCF50712E61E1FC8536A324F1FC850D}
