version: "3"
services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:latest
    container_name: 'gssg-assets-db'
    ports:
      - '31006:31006'
    environment:
      MYSQL_DATABASE: 'gssg-assets'
      MYSQL_ROOT_PASSWORD: 'local-password-123!'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes:
      - '~/mysql:/var/lib/mysql'
